// <auto-generated />
namespace CodeFirstDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedUserClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedUserClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201904230056144_addedUserClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
